### ISSUE TITLE
What authentication-related fields do we need?

### ISSUE THREAD

**Issue by mirw** [Metaswitch/swagger-rs#17]
As discussed in https://github.com/Metaswitch/swagger-rs/pull/14#issuecomment-327750398, it's not clear what authentication fields we need in the context?

@kw217, over to you to consider.

**Comment by kw217** [comment]
Please also reinstate the comments which were present in #14 and rolled back when that was rolled back. Comments are good!

**Comment by kw217** [comment]
We've been using this for more than two years now, so what we have must be sufficient. Happy to close.
