### ISSUE TITLE
`composites::CompositeNewService` will fail in Rust 1.26

### ISSUE THREAD

**Issue by bjgill** [Metaswitch/swagger-rs#30]
This currently fails in beta (see https://travis-ci.org/Metaswitch/swagger-rs/jobs/357325958).

```
failures:
---- src/composites.rs - composites::CompositeNewService (line 91) stdout ----
	error: unknown start of token: `
  --> src/composites.rs:99:23
   |
10 | <use as you would any `NewService` instance>
   |                       ^
   |
help: unicode character '`' (Grave Accent) looks like ''' (Single Quote), but it's not
  --> src/composites.rs:99:23
   |
10 | <use as you would any `NewService` instance>
   |                       ^
thread 'rustc' panicked at 'couldn't compile the test', librustdoc/test.rs:306:13
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

Discovered by crater - https://github.com/rust-lang/rust/issues/49935

**Comment by bjgill** [comment]
@tca-ms - I think this was introduced by https://github.com/Metaswitch/swagger-rs/pull/28/files#diff-6fbf80ae5818a7af98f1648494b302dcR100. At a glance, it looks as if its an example that either needs to be marked as ignore, or made into valid Rust. Would you be happy to fix this up as the original author?

**Comment by tca-ms** [comment]
@bjgill I noticed this, not sure how it got through the CI. I've added "ignore" in [this](https://github.com/Metaswitch/swagger-rs/pull/29) MR (as part of an unrelated change). Is that OK, or would you rather I made a MR with just this fix?

**Comment by bjgill** [comment]
Excellent - that's fine, thanks.

**Comment by bjgill** [comment]
Now fixed in master. Thank you.
